spring:
  application:
    name: spring-redis

  # CẤU HÌNH ĐÚNG PHẢI CÓ 'data'
  data:
#    mongodb:
#      uri: mongodb://admin:admin123@localhost:27017/school?authSource=admin
#      auto-index-creation: true # Giúp annotation @Indexed(unique=true) hoạt động

  # Tùy chỉnh Jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+7
    serialization:
      indent-output: true

  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

server:
  servlet:
    context-path: /api
  port: 8083

gg:
  jte:
    developmentMode: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.mongodb.driver.cluster: WARN